### ISSUE TITLE
Importación: Obras, Editar: Fechas en diferentes pestañas

### ISSUE THREAD

**Issue by ElisaArteGlobal** [emamnuelmesa/Arte-Global#10]
Cuando se importa del excel las fechas ocurren varios errores:
1- No me guarda las fechas en el excel de importación
2- una vez finalizado el proceso de importación, en pestaña Conservación y Localización aparecen en los campos de fechas 01/01/1980, cuando no se ha puesto nada

**Comment by luismoraleda** [comment]
1- Actualmente el excel de importación tiene dos fechas; fechaTasación y fechaCompra. El resto de fechas aparecerán vacías al no estar cargadas.
2. Se corrige fecha por defecto ante un campo vacío.
