### ISSUE TITLE
Con Avast no me deja acceder al area privada

### ISSUE THREAD

**Issue by DanielRedCollectors** [emamnuelmesa/Arte-Global#1031]
Buenas tardes Miguel,

Parece que hemos detectado un bug desde el ultimo cambio de diseño del area privada. Cuando queremos acceder al área privada  teniendo activado Avast como antivirus, este lo detecta como una posible pagina peligrosa y no nos deja entrar.

<img width="430" alt="Captura de pantalla 2021-07-30 a las 17 38 04" src="https://user-images.githubusercontent.com/78749645/127677207-7ff2ad5c-7410-4bfa-a55f-050467d4a9f3.png">

Gracias.

**Comment by JavierFernandezQuasar** [comment]
Buenos días Daniel,

Hemos probado desde un ordenador con Avast el acceso al área privada y no nos ha detectado ninguna posible amenaza. Lo que tendrás que hacer será desde el propio Avast permitir dicho sitio web.
Añadir que el propio antivirus de Windows 10, es el antivirus más fiable.

Un saludo.
