### ISSUE TITLE
Bug galería (Camara Oscura): no se puede quitar una feria vinculada a una obra

### ISSUE THREAD

**Issue by prensa-redcollectors** [emamnuelmesa/Arte-Global#1041]
1. Una vez que hemos asignado obras a exposiciones o ferias, no podemos quitarlas de esa feria o expo
![image.png](https://images.zenhubusercontent.com/6021650d3635b803e1148b43/e8ba02e4-ee42-4c2e-8096-16c82271a400)

2. Por lo que debería aparecer la primera opción cuando damos a "Feria Expo" que sea "Quitar de la feria asignada"
![image.png](https://images.zenhubusercontent.com/6021650d3635b803e1148b43/d6fea423-98ee-467a-b74d-a167ca7dc290)

Además, dentro de la ficha de cada obra tampoco funciona. 

1. Si entramos a editar una obra en concreto y vamos a la feria expo:
![image.png](https://images.zenhubusercontent.com/6021650d3635b803e1148b43/fed0e7f8-cec8-4a1c-9562-cef2473b0058)

2. Seleccionamos la opción de Feria/expo para eliminarla de la anterior:
![image.png](https://images.zenhubusercontent.com/6021650d3635b803e1148b43/61d0ff14-c695-4332-b502-259a41dff5fc)

3. De esta forma no se guarda lo que hemos seleccionado:
![image.png](https://images.zenhubusercontent.com/6021650d3635b803e1148b43/6873f480-0a17-4907-bbfd-86be5c5f25a4)

**Comment by miguelGonzalezQuasar** [comment]
Hola Silvia,

Las ferias se desvinculan de las obras desde el histórico de la pestaña "obra" al editarla:

![image](https://user-images.githubusercontent.com/49310555/132525533-eba4ee62-ef07-4a38-8195-da194bc20fbc.png)

Si está todo ok, cierras el ticket porfa.

Muchas gracias,
Un saludo,

**Comment by prensa-redcollectors** [comment]
Buenos días, Miguel.

Perfecto, muchas gracias. Cerramos el ticket.

Un saludo,

*Silvia Zapata *
*Departamento de Ventas y Marketing*
*Sales and Marketing *
