### ISSUE TITLE
Bug usuario coleccionista: Mis datos

### ISSUE THREAD

**Issue by ElisaArteGlobal** [emamnuelmesa/Arte-Global#106]
2018-01-08 Bug
Sigue sin salir los datos en el pie de página correctos. Faltaría dirección, ciudad, CP. Adjunto pantallazo de ejemplo
![image](https://user-images.githubusercontent.com/33623863/34669445-f7346cc2-f471-11e7-8350-49121c364396.png)
Ver el documento adjunto el ejemplo

2018-01-03 Bug
Usuario coleccionista: 
1- Guardo el logo en la imagen  y la dirección en Mis datos
![image](https://user-images.githubusercontent.com/33623863/34560586-96bd3636-f146-11e7-97d2-c7abfc776d46.png)
2- Genero dossier y no incluye ni el logo ni los datos como en galerías
![image](https://user-images.githubusercontent.com/33623863/34560582-906b2d42-f146-11e7-8479-6cf5e3454f17.png)

**Comment by luismoraleda** [comment]
![image](https://user-images.githubusercontent.com/33345619/34670756-fcaab4b2-f477-11e7-97d0-1045fd47ea99.png)

Prueba ahora
