### ISSUE TITLE
Bug: colecc/galerías compartir misma obra con dos usuarios distintos

### ISSUE THREAD

**Issue by ElisaArteGlobal** [emamnuelmesa/Arte-Global#127]
si compartes la misma obra con dos usuarios distintos, la obra la duplica
[https://app.zenhub.com/files/108112751/ab33448e-443a-48fb-a66c-d4fe6d240fcc/download](https://app.zenhub.com/files/108112751/ab33448e-443a-48fb-a66c-d4fe6d240fcc/download)

**Comment by luismoraleda** [comment]
Actualmente no esta desarrollado para compartir con varios usuarios, únicamente con Arteglobal, aunque en el momento del bug si se visualizaba.
