### ISSUE TITLE
Importación- Bugs excel: Menús desplegables

### ISSUE THREAD

**Issue by ElisaArteGlobal** [emamnuelmesa/Arte-Global#13]
Importación- Bugs excel: Menús desplegables: Disponibilidad, Categoría, Soporte, Divisa .... a partir de la segunda fila en nueva versión de excel no funciona.
Hacer compatible con todas las versiones del excel

**Comment by luismoraleda** [comment]
En versiones inferiores a 2010 no está disponible listado con campos situados en otra hojas.
