### ISSUE TITLE
Bug ARCO: no ha guardado categoría

### ISSUE THREAD

**Issue by ElisaArteGlobal** [emamnuelmesa/Arte-Global#163]
estas dos obras de esta galería, cuando hemos ido a clasificarlas por temática y lenguaje, no tenía categoría guardada ¿pero es obligatorio no?
Goran Trbuljak 
Monochrome 2/X (yellow) 
1991 
Arco18 
GalerijaGregorPodnar
 
Goran Trbuljak 
Art in America 
1995 
Arco18 
GalerijaGregorPodnar

**Comment by luismoraleda** [comment]
La categoría no ha sido guardada porque habrá sido creada por registro excel. Por aquí solo se avisa si hay un campo obligatorio que no esta rellenado pero se puede guardar.
En el excel de ejemplo he subrayado los campos obligatorios.
![image](https://user-images.githubusercontent.com/33345619/35857789-7dbd7b42-0b3a-11e8-85ae-fa6105dfe315.png)
