### ISSUE TITLE
Importación: Menú - Empresa/Institución (Histórico)

### ISSUE THREAD

**Issue by ElisaArteGlobal** [emamnuelmesa/Arte-Global#17]
![image](https://user-images.githubusercontent.com/33623863/32992022-f4fe4c78-cd45-11e7-9e32-fcc92b952a91.png)
Empresa/Institución (Histórico) qué es?? No lo encuentro en RedCollectors pero está en la plantilla de Excel. Es Nombre de Depositante en pestaña Depósito? Si es así cambiar

**Comment by luismoraleda** [comment]
jaja en el listado de excel lo coloreé en rojo(para revisar). Tampoco sé a que pertenece. 
El nombre de depositante se encuentra asociado a los contactos, puede que anteriormente fuera para ese campo cuando era libre, lo elimino del archivo excel.
