### ISSUE TITLE
Contactos: Teléfonos y emails

### ISSUE THREAD

**Issue by ElisaArteGlobal** [emamnuelmesa/Arte-Global#20]
Incluir campos para los tres tipos de teléfonos (teléfono, móvil y otro) y dos de email (email, otro)
![image](https://user-images.githubusercontent.com/33623863/33081113-bed760fe-ced9-11e7-8f4f-9727b3620265.png)

**Comment by luismoraleda** [comment]
Se unificara la pestaña de contacto de editar y crear en una única.
