### ISSUE TITLE
Contactos: categoría: duda

### ISSUE THREAD

**Issue by ElisaArteGlobal** [emamnuelmesa/Arte-Global#23]
Luis, si alguien crea las categorías diferentes pero iguales de : galería, galeria, Galerías, galerías ¿se puede avisar al usuario? cuál podría ser la solución?
gracias :)
PD Mola esto del github  jeje

**Comment by luismoraleda** [comment]
Lo he planteado de la siguiente manera :
![anadir etiqueta a un contacto](https://user-images.githubusercontent.com/33345619/33425782-0da2752e-d5c0-11e7-8609-52bcccebabab.png)
