### ISSUE TITLE
BugAR: Guardar Dossiers generados en menú Informes

### ISSUE THREAD

**Issue by ElisaArteGlobal** [emamnuelmesa/Arte-Global#328]
Los documentos tipo Dossier que generamos no se guardan en el menú Informes

**Comment by luismoraleda** [comment]
En un bug anterior se quedo en que el menú informes estarían solo los de este tipo, dejando los de tipo dossier ; "Dossier" y "Certificado de autenticidad" para la pestaña Dossier en la ventana de contacto.

**Comment by ElisaArteGlobal** [comment]
Es que las pestañas Dossier e Informes de cada ficha de contacto son independientes del menú Informes. En la ventana de contacto está correctamente indicado; sin embargo, en el menú informes deben adjuntarse todos los informes que el usuario genere, incluidos los Dossiers
