### ISSUE TITLE
Plantilla importación obra: Incluir Fecha inicio-Depósito

### ISSUE THREAD

**Issue by ElisaArteGlobal** [emamnuelmesa/Arte-Global#47]
Plantilla importación obra: Incluir Fecha inicio-Depósito justo en la columna entre "nombredepositante" y "precioIvaObraDeposito"
Ojo pq ahora si tengo una fecha inicio, lo pongo en el menú como Fecha inicio-Localización y lo saca en las dos fechas, en la de arriba y en Fecha inico-Depósito.
Con esta modificación, se pondrán diferenciar las dos fechas
Ver ejemplo en el excel anterior enviado

**Comment by luismoraleda** [comment]
Solucionado, han pasado a llamarse en el excel como;  fechaInicioLocalizacion y fechaInicioDeposito
