### ISSUE TITLE
Bug importación: no me guarda las imágenes asociada a las obras (paso 2 importación)

### ISSUE THREAD

**Issue by ElisaArteGlobal** [emamnuelmesa/Arte-Global#48]

**Comment by luismoraleda** [comment]
Edito el nombre de dos imagenes poniendo el mismo nombre que se encuentra en el campo de imagen del archivo  Excel, las comprimo en formato zip y las importa bien.
Prueba con este fichero de dos imagenes ya adaptadas al Excel con el que estamos trabajando esta mañana y me dices.
[Imagenes 2 registros.zip](https://github.com/emamnuelmesa/Arte-Global/files/1517644/Imagenes.2.registros.zip)
