### ISSUE TITLE
Bug Gal (F2). No es posible guardar información en la pestaña de Localización

### ISSUE THREAD

**Issue by ElisaArteGlobal** [emamnuelmesa/Arte-Global#498]
En la referencia SS-0076 (usuario F2) no se puede actualizar información de Localización

**Comment by luismoraleda** [comment]
Probado y no se aprecia anomalía. Puede que el usuario este intentando modificar el nombre de contacto y este no es modificable, se trata de un campo auto completado que muestra la lista de contactos, si quiere modificar el nombre debe irse al área correspondiente.
