### ISSUE TITLE
Duda: Importación imágenes

### ISSUE THREAD

**Issue by ElisaArteGlobal** [emamnuelmesa/Arte-Global#52]
Me estaba volviendo loca intentando importar las imágenes y no me dejaba, al final me he dado cuenta que si importas dos obras sólo puedes poner sus dos imágenes, si pones más obras y dos imágenes no te deja ... ¿q te parece?

**Comment by luismoraleda** [comment]
Solucionado, creo que ya no falla, ajuste un parámetro en la función que extrae el fichero.
