### ISSUE TITLE
Bug: Galería (Facturas): diseño facturas desde ipad

### ISSUE THREAD

**Issue by ElisaArteGlobal** [emamnuelmesa/Arte-Global#543]
Al generar facturas desde ipad, se pierde el diseño de la factura (fuente, tabla, saltos de línea, etc)
![image.png](https://images.zenhubusercontent.com/5a098a0d8a75884b90872ae7/f55304fb-be9d-4e92-95f6-5f6ab00ef730)

Pero la factura se visualiza bien si la abrimos desde PC

**Comment by luismoraleda** [comment]
El diseño de la factura generada depende del programa que se tenga instalado en cada dispositivo ya que está programado para .docx y .pdf
