### ISSUE TITLE
Bug: Gal/Col. (Volcado de imágenes): no admite nombres de archivo con punto(.) ni almohadilla (#)

### ISSUE THREAD

**Issue by ElisaArteGlobal** [emamnuelmesa/Arte-Global#546]
El volcado no admite archivos de imagen cuyo nombre contenga punto (.) o almohadilla (#)
No sabemos si habrá algún otro caracter que no admita... ¿lo sabéis vosotros? ¿probamos todos?

**Comment by luismoraleda** [comment]
Adjuntado por email listado de caracteres especiales.

Un saludo,
