### ISSUE TITLE
Contactos- Opciones: eliminar y categorías

### ISSUE THREAD

**Issue by ElisaArteGlobal** [emamnuelmesa/Arte-Global#55]
Botón opciones que incluye categorías y eliminar contactos
[2017-11-30 Opciones Contactos.pdf](https://github.com/emamnuelmesa/Arte-Global/files/1518671/2017-11-30.Opciones.Contactos.pdf)

**Comment by luismoraleda** [comment]
Repasando me he dado cuenta que la acción de eliminar contacto no la quieres como pensé cuando hablamos por teléfono.
En estudio

**Comment by ElisaArteGlobal** [comment]
Hola Luis
No te preocupes, déjala por ahora así que para borrar todo de golpe nos va
hoy.
Gracias

 Elisa Hernando Calero
 Directora

+ 34 91 591 98 85
