### ISSUE TITLE
eh@arteglobal.es Dossier no descarga aunque luego aparece vinculado al contacto

### ISSUE THREAD

**Issue by ElisaArteGlobal** [emamnuelmesa/Arte-Global#561]
Si genero un dossier desde eh, no se descarga pero si voy al contacto aparece archivado en la pestaña de dossier

**Comment by luismoraleda** [comment]
Hemos estado haciendo pruebas y en principio parece que descarga bien, a ver cuando publiquemos en pruebas si ya no da más errores y si no lo miramos con mas profundidad.
