### ISSUE TITLE
Bug: Col/Gal. Informes: etiquetas. Texto se sale del margen cuando el campo técnica es muy largo

### ISSUE THREAD

**Issue by ElisaArteGlobal** [emamnuelmesa/Arte-Global#562]
La maquetación de la etiqueta tiene el margen derecho sin ajustar y cuando el campo de "Técnica" es muy largo el texto se sale de la etiqueta.
Adjunto ejemplo generado por la galería Alarcón Criado:
[https://app.zenhub.com/files/108112751/532dc877-139b-4fe9-98a6-c92a1c6ffdd1/download](https://app.zenhub.com/files/108112751/532dc877-139b-4fe9-98a6-c92a1c6ffdd1/download)

**Comment by luismoraleda** [comment]
Tal y como comentamos en la última reunión, este bug no se realiza, así que lo pasamos a pruebas con el resto.
