### ISSUE TITLE
Bug: Usuario Álvaro Alcázar. Obras presentan imágenes que no corresponden

### ISSUE THREAD

**Issue by ElisaArteGlobal** [emamnuelmesa/Arte-Global#565]
Alvaro Alcázar nos envía incidencia similar a la ya ocurrida en septiembre: muchas obras presentan una imagen que no les corresponde. En septiembre se trataba de imágenes que ni siquiera procedían de sus piezas. Ahora ocurre con imáges de su base de datos, pero decolocadas y añadidas a obras de un artista incorrecto.
Adjunto tres ejemplos:
![Captura de pantalla 2019-03-07 a las 9.59.13.png](https://images.zenhubusercontent.com/5a098a0d8a75884b90872ae7/d16bc105-8bd1-4de1-a911-f2a29140756e)![Captura de pantalla 2019-03-07 a las 9.59.19.png](https://images.zenhubusercontent.com/5a098a0d8a75884b90872ae7/23f6c89a-1bc1-43a0-92dd-f89c3a1dc0a0)![Captura de pantalla 2019-03-07 a las 9.59.36.png](https://images.zenhubusercontent.com/5a098a0d8a75884b90872ae7/6f6d10da-57a7-48da-bb54-26bc7e33c0a1)

Me dicen que esto  ocurre con muchas obras y de forma intermitente: un día están bien pero al día siguiente cambia la imagen de la obra por una errónea

Comprobar por favor dónde está el fallo para solucionarlo definitivamente y cómo restaurar las imágenes equivocadas.

**Comment by luismoraleda** [comment]
A la espera de contestación de la galería (poner obras con número referencia para mejor seguimiento).
Se sigue haciendo seguimiento del "cambio" de imágenes en las obras del bug.
En cuanto a la imagen rotada de la obra con número de referencia GAA09-118, se ha corregido porque en el volcado de las mismas se hicieron con la imagen rotada. A ser posible, que nos hagan listado de todas aquellas obras que les suceda lo mismo para arreglarlo porque están volcadas desde un mismo Excel.

**Comment by ElisaArteGlobal** [comment]
Añado ejemplos que he ido enviando por mail de este bug para que también consten en el ticket.
Este pantallazo es de obras de Daniel Canogar que o bien no tienen imagen o, las dos que tienen, corresponden a obras de otro usuario. (20/03/2019)
![image](https://user-images.githubusercontent.com/33623863/55614720-f1307200-578d-11e9-8d55-4aaec9b6aa17.png)
