### ISSUE TITLE
Bug y Mod: Usuario Alarcón Criado. Campo de Stiuación

### ISSUE THREAD

**Issue by ElisaArteGlobal** [emamnuelmesa/Arte-Global#571]
1. A Alarcón Cirado le ha ocurrido la duplicación de la Siutación "Galería" de forma que aunque está escrito exactamente igual, hay dos situaciones distintas. Por favor, unificar todas bajo una sola

2. Han reducido el número de Situaciones que van a utilizar a las siguientes:

- Galería 
- RETIRADA  ( escrito en mayusculas)
-Taller Artista
-Almacén
-Sin producir
-Prestada

Por favor eliminar todas las situaciones restantes. Me dicen que ya no hay obras con situaciones distintas a las señaladas arriba.

**Comment by luismoraleda** [comment]
Hola,

Tienen obras en otras situaciones como por ejemplo "Gentzane",  "Hato Verde", "PERDIDA EN UN TRANSPORTE INDEMNIZADA",  "20X24""...
Que unifiquen por favor todas las obras a las situaciones que van a utilizar.

Gracias, un saludo

**Comment by ElisaArteGlobal** [comment]
Esperar a que la galería envíe su lista definitiva de situaciones a limpiar, porque aún no han vaciado todas las situaciones que quieren eliminar
