### ISSUE TITLE
Bug: importación de contactos. adjunto excel

### ISSUE THREAD

**Issue by ElisaArteGlobal** [emamnuelmesa/Arte-Global#58]
[2017-12 prueba contactos.xlsx](https://github.com/emamnuelmesa/Arte-Global/files/1525178/2017-12.prueba.contactos.xlsx)

**Comment by luismoraleda** [comment]
Hay una columna en el Excel que su campo título se encuentra sin nombre, es decir, vacío provocando un error en la importación. 
Solucionado aunque se creen campos sin título no petara.
Prueba de nuevo
