### ISSUE TITLE
Particular: Bug Asesoría en Venta

### ISSUE THREAD

**Issue by ElisaArteGlobal** [emamnuelmesa/Arte-Global#584]
Si pincho en asesoría en venta sale error, debería llevar a un formulario. Adjunto documento
[https://app.zenhub.com/files/108112751/44d1829f-db54-4fb1-a026-302256f43880/download](https://app.zenhub.com/files/108112751/44d1829f-db54-4fb1-a026-302256f43880/download)
![Captura de pantalla 2019-03-28 a las 14.25.07.png](https://images.zenhubusercontent.com/5a098a0d8a75884b90872ae7/11735618-b1d5-4ba6-8539-ebdbebc14b2e)

**Comment by miguelGonzalezQuasar** [comment]
Prueba

**Comment by miguelGonzalezQuasar** [comment]
A la espera del documento con el diseño de la nueva vista
