### ISSUE TITLE
Bug. Usuario: prensa@arteglobal.com. Búsqueda avanzada no funciona

### ISSUE THREAD

**Issue by ElisaArteGlobal** [emamnuelmesa/Arte-Global#591]
Si busco por galería Ponce+Robles, me salen más de 10.000 obras
![image.png](https://images.zenhubusercontent.com/5a098a0d8a75884b90872ae7/8b2a752f-9b24-43cc-8a64-0000c0dfa857)

Si busco por apellido de artista: Plensa, me salen también 10814 obras
![image.png](https://images.zenhubusercontent.com/5a098a0d8a75884b90872ae7/cabb60f6-b69c-484d-8971-3cd744930e27)

Si busco por tema. Arquitectura-urbano, salen 10732 obras
![image.png](https://images.zenhubusercontent.com/5a098a0d8a75884b90872ae7/9065f835-90f4-4f04-a2c4-3297236122e4)

**Comment by miguelGonzalezQuasar** [comment]
Este usuario ha sido eliminado en real.

Un saludo
