### ISSUE TITLE
Bug: 3mas1. Localización. Excel, pruebas y privado no coinciden. En privado hay un histórico con fecha posterior

### ISSUE THREAD

**Issue by ElisaArteGlobal** [emamnuelmesa/Arte-Global#599]
16-4-2019
he localizado obras con fecha de marzo con mismo problema. revisar por favor
[2019-4-16  bug LOCALIZACIÓN 3MAS1.pdf](https://github.com/emamnuelmesa/Arte-Global/files/3085735/2019-4-16.bug.LOCALIZACION.3MAS1.pdf)
14-4-2019
excel subido pero Manuel dice que es por base de datos diferentes desde abril 2019
[https://app.zenhub.com/files/108112751/d84af7c2-39c3-4c3f-8fa3-25968d2d345e/download](https://app.zenhub.com/files/108112751/d84af7c2-39c3-4c3f-8fa3-25968d2d345e/download)

**Comment by miguelGonzalezQuasar** [comment]
La base de datos de pruebas lleva más de un mes sin actualizarse de la real.
Se solucionaría actualizándose pero estamos a la espera de autorización por vuestra parte.

Un saludo
