### ISSUE TITLE
Importación: Nombre y apellido del artista

### ISSUE THREAD

**Issue by luismoraleda** [emamnuelmesa/Arte-Global#6]

**Comment by ElisaArteGlobal** [comment]
No identifica el nombre del artista si lo ponemos en la columna. He probado tanto con artistas nuevos (que no están en el listado existente) o con artistas existentes (ej. demog Pablo Picasso) y no lo guarda en las obras

**Comment by luismoraleda** [comment]
Controlado espacios en blanco al final del nombre y del apellido al crear el artista. En el caso de Pablo Picasso tenía espacios en blanco al final del nombre y no igualaba.
Crea también un artista nuevo sino está en la base de datos.
