### ISSUE TITLE
Bug no me deja importar obras de otro usuario Uría

### ISSUE THREAD

**Issue by ElisaArteGlobal** [emamnuelmesa/Arte-Global#60]
[prueba importación uria.xlsx](https://github.com/emamnuelmesa/Arte-Global/files/1530415/prueba.importacion.uria.xlsx)

**Comment by luismoraleda** [comment]
He importado un registro del excel en demog@redcollectors.com y no hay problemas.
También he probado con la totalidad con el usuairo manuel.mesa@quasar.com.es sin presentar problemas.
