### ISSUE TITLE
Bug Localización. Quitar "Añadir Nuevo Estado"

### ISSUE THREAD

**Issue by MartaSoriano** [emamnuelmesa/Arte-Global#656]
[https://app.zenhub.com/files/108112751/48691168-d51a-4784-b2f5-dc9b997d855f/download](https://app.zenhub.com/files/108112751/48691168-d51a-4784-b2f5-dc9b997d855f/download)

**Comment by ElisaArteGlobal** [comment]
Se queda el espacio en blanco y confunde, eliminar ese espacio en blanco
![Uploading image.png…]()
