### ISSUE TITLE
Bug_galeria 3punts_imagen rota

### ISSUE THREAD

**Issue by yuechen-arteglobal** [emamnuelmesa/Arte-Global#687]
[https://app.zenhub.com/files/108112751/4ddff498-9bc3-4bb9-af71-5826951d5593/download](https://app.zenhub.com/files/108112751/4ddff498-9bc3-4bb9-af71-5826951d5593/download)

**Comment by miguelGonzalezQuasar** [comment]
Hola Yue,
¿Podrías averiguar con que navegador subieron las fotos y con qué dispositivo?

Gracias,

Un saludo,
