### ISSUE TITLE
Bug: Obras eliminar las piezas pero las imágenes quedan como en archivo

### ISSUE THREAD

**Issue by ElisaArteGlobal** [emamnuelmesa/Arte-Global#69]
Si eliminas las piezas con sus imágenes y luego las vuelves a subir, les asignas las imágenes que tenías antiguamente, como si las guardase en un histórico. Eso puede generar cierta susceptibilidad entre algunas personas ya que pueden pensar que aunque ellos borran, no se eliminan (aunque siempre es bueno decir que es un back up por si acaso)

**Comment by luismoraleda** [comment]
Tendremos que informar que es un backup. 
No hemos podido mover o eliminar la imagen porque esta siendo utilizada por otro proceso que no somos capaces de controlar. A día de hoy no se puede
