### ISSUE TITLE
Bug:  OBra edición, ediciones totales-

### ISSUE THREAD

**Issue by ElisaArteGlobal** [emamnuelmesa/Arte-Global#71]
Las obras que F2 le da error para guardarlos manualmente son:
Número de referencia JC-0031 y JC-0061; La edición es 1 de 5 y 2 de 5

**Comment by luismoraleda** [comment]
El problema se encontraba en que no mostraba el mensaje de campo requerido en la divisa, por lo que la acción no se realizaba, no guardando ni editando ningún valor.
Probar con la referencia JC-0061. Mostrará que hay que añadir divisa, añadirla e insertar valores de edición.
