### ISSUE TITLE
Bug: Contactos- País USA- Estados Unidos

### ISSUE THREAD

**Issue by ElisaArteGlobal** [emamnuelmesa/Arte-Global#73]
si al importar el país pone USA y no Estados Unidos, no lo reconoce

**Comment by luismoraleda** [comment]
No está preparado para reconocer USA, se añade.

**Comment by ElisaArteGlobal** [comment]
ok gracias

 Elisa Hernando Calero
 Directora

+ 34 91 591 98 85


2017-12-13 11:04 GMT+01:00 luismoraleda <notifications@github.com>:
