### ISSUE TITLE
BUG_usuario Antonioramon

### ISSUE THREAD

**Issue by yuechen-arteglobal** [emamnuelmesa/Arte-Global#781]
Hola Miguel, 
Hay1 bug que tiene el usuario de antonioramon: 
1. no se puede incluir el logo de la empresa a perfil de usuario, el boton de "cambiar" no funciona. 
![image.png](https://images.zenhubusercontent.com/5d6f75e226c94948dbb43269/b3c107de-1925-43ea-a4e9-438a2f2c0e8f)

Muchas gracias

**Comment by miguelGonzalezQuasar** [comment]
Hola Yue,

Los usuarios admin (yue, info y antonioramon) no tienen habilitado el botón "Mis Datos" que es dónde se puede subir la imagen de la empresa (galería, corporativo), entiendo que se pondría así en su día porque son perfiles administradores.

El botón cambiar al que haces referencia, es una funcionalidad que está aún por desarrollar. Aquí iría en ese caso la foto del usuario.

Con todo esto, ya me dices:
- si hay que desarrollar la funcionalidad "cambiar".
- si hay que habilitar a los admin de obras y de galerias/coleccionistas el botón "Mis Datos".
- o ambas.

Gracias, 

Un saludo,
