### ISSUE TITLE
Bug 6- etiquetas, espacios

### ISSUE THREAD

**Issue by ElisaArteGlobal** [emamnuelmesa/Arte-Global#86]
Mejorar los espacios para que esté más equilibrado y centrado todo en las dos opciones con y sin imagen:
A) Etiquetas con imagen
Dar dos espacios arriba y luego la imagen (para que no aparezca pegada al ras de la etiqueta), desde la imagen hasta el nombre del artista, dos espacios. Abajo está el nombre de la galería, debajo incluir la web y luego otros dos espacios. A continuación dos imagenes de cómo quedaría con espacios y después los símbolos de formato visibles:
![image](https://user-images.githubusercontent.com/33623863/34082375-36ae6c34-e35d-11e7-87d8-3fa2dcc5453f.png)
![image](https://user-images.githubusercontent.com/33623863/34082384-707e1a22-e35d-11e7-88cf-15f4ab9f5eb1.png)
B) Etiquetas sin imagen
Dar ocho espacios arriba hasta el nombre del artista. Abajo está el nombre de la galería, debajo incluir la web y luego otros dos espacios. A continuación dos imagenes de cómo quedaría con espacios y después los símbolos de formato visibles:
![image](https://user-images.githubusercontent.com/33623863/34082428-979c6b3a-e35e-11e7-8048-3c200c895e01.png)
![image](https://user-images.githubusercontent.com/33623863/34082430-9bc4d148-e35e-11e7-9079-a6048b497c70.png)

**Comment by luismoraleda** [comment]
![image](https://user-images.githubusercontent.com/33345619/34153129-478328f6-e4b1-11e7-8c40-2dcbeaee837c.png)
En algunas imágenes, tales como esta, y con descripción técnica algo más extensa quedaría muy pegado si hubiese web.
Dejo en un espacio desde la parte superior a la imagen;

![image](https://user-images.githubusercontent.com/33345619/34153193-7a966f14-e4b1-11e7-8ff0-f62a180cd945.png)

**Comment by ElisaArteGlobal** [comment]
ok, recuerda que sino hay imagen, el texto también tiene que estar cuadrado
dentro de todos los espacios

 Elisa Hernando Calero
 Directora

+ 34 91 591 98 85
