### ISSUE TITLE
Bug: error al cambiar contraseña usuario eh@arteglobal.es y pruebauria

### ISSUE THREAD

**Issue by ElisaArteGlobal** [emamnuelmesa/Arte-Global#88]
Al intentar cambiar la contraseña de eh@arteglobal.es me sale el mismo error que cuando hacía lo mismo con pruebauria@arteglobal.es
![image](https://user-images.githubusercontent.com/33623863/34160753-85d3b4aa-e4ce-11e7-8439-d5bd4580b523.png)

**Comment by luismoraleda** [comment]
La he cambiado con el procedimiento normal y no me ha dado problemas.
La nueva contraseña es:
Superpassword2.
